# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5d3ae695b600cdf59ade0a0ba57d3a6562486233a1aad5135e6215f3f7366bca0a4ce0c017390b71021871130616bc246153a05e932b7ac7c385d337933df60

test:
  secret_key_base: 5024ae0923114b0d93c9be25ea332937899fcf43f3ea1d3f2123d0d3ef5e274dd054ba964d5b28830b959644c7ab5c12312f6dbc89dd1acad463d7963532a544

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
